<a href="https://colab.research.google.com/github/qfx4yk/PyTorch/blob/main/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import math

# Initializing a Tensor

A tensor is a multidimensional arra containing floating-point, integer, or boolean data.

In [2]:
# Simplest way to create a tensor in which you do not initialize it with values
x = torch.empty(3, 4) # 3 x 4 tensor; 2D with 3 rows and 4 columns
print(type(x)) # object type = torch.Tensor, which is alias for torch.FloatTensor
print(x)

<class 'torch.Tensor'>
tensor([[-2.8014e+21,  3.3215e-41,  0.0000e+00,  0.0000e+00],
        [ 4.2039e-45,  1.5414e-44,  4.2039e-45,  1.6816e-44],
        [ 1.6241e-42,  0.0000e+00, -2.8014e+21,  3.3215e-41]])


In [3]:
# Initializing your tensor with some value (e.g. all zeros, all ones, or random values)
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])


In [4]:
# Creating a 6x4 matrix filled with zeros, and query its datatype to find out that the zeros are 32-bit floating point numbers, which is the default PyTorch
z = torch.zeros(6,4)
print(z)
print(z.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [5]:
# Creating a 6x4 matrix filled with ones expressed as integers
L = torch.ones((6,4), dtype=torch.int32)
print(L)
print(L.dtype) # You see that when we do change/override the default, the tensor helpfully reports this when printed

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
torch.int32


In [6]:
# Tensors can be created directly from data. The data type is automatically inferred
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
# Tensors can be created from NumPy arrays and vice versa
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [8]:
# Tensors can be created from another tensor. The new tensor retains the properties (shape, datatype) of the arguement tensor, unless explicitly overriden
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3971, 0.7544],
        [0.5695, 0.4388]]) 



In [9]:
# "shape" is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor
shape = (2,3,4,1)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[[0.6387],
          [0.5247],
          [0.6826],
          [0.3051]],

         [[0.4635],
          [0.4550],
          [0.5725],
          [0.4980]],

         [[0.9371],
          [0.6556],
          [0.3138],
          [0.1980]]],


        [[[0.4162],
          [0.2843],
          [0.3398],
          [0.5239]],

         [[0.7981],
          [0.7718],
          [0.0112],
          [0.8100]],

         [[0.6397],
          [0.9743],
          [0.8300],
          [0.0444]]]]) 

Ones Tensor: 
 tensor([[[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]]]) 

Zeros Tensor: 
 tensor([[[[0.],
          [0.],
          [0.],
      

## Random Tensors and Seeding

Initializing tensors, such as a model’s learning weights, with random values is common but there are times - especially in research settings - where you’ll want some assurance of the reproducibility of your results. Manually setting your random number generator’s seed is the way to do this.

In [10]:
# It is common to initialize learning weights randomly, often with a specific seed for the random number generators that you can reproduce your results on subsequent runs
torch.manual_seed(1729) # here, we seed the pytorch random number generator with a specific number to generate a random tensor
r1 = torch.rand(2,2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2,2)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1729) # re-seeding random number generator with same input
r3 = torch.rand(2,2)
print('\nShould match r1:')
print(r3) # repeats values of r1 because of re-seed

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [11]:
# Another seeding example
# Manually setting the RNG’s seed resets it, so that identical computations depending on random numbers should, in most settings, provide identical results.
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3) # matches random1
print(random3)

random4 = torch.rand(2, 3) # matches random2
print(random4)

random5 = torch.rand(2,3)
print(random5)

torch.manual_seed(1729)
random6 = torch.rand(2,3)
print(random6)

random7 = torch.rand(2,3)
print(random7)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## Tensor Shapes

Often, when you’re performing operations on two or more tensors, they will need to be of the same shape - that is, having the same number of dimensions and the same number of cells in each dimension.

In [12]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[-2.8043e+21,  3.3215e-41, -2.8049e+21],
         [ 3.3215e-41,  8.9683e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  1.7970e-13],
         [ 3.3208e-41, -3.2806e+21,  3.3215e-41]]])
torch.Size([2, 2, 3])
tensor([[[ 2.0445e-13,  3.3208e-41,  0.0000e+00],
         [ 2.3510e-38, -2.1867e+18,  3.3215e-41]],

        [[ 1.0842e-19,  0.0000e+00,  4.7399e+16],
         [ 9.3233e-09,  8.0671e+17,  5.7453e-44]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


# Attributes of a Tensor

In [13]:
# Tensor attributes describe their shape, datatype, and the device on which they are stored
tensor = torch.rand(2,6)

print(f"Here is my tensor: {tensor}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Here is my tensor: tensor([[0.5062, 0.8469, 0.2588, 0.2707, 0.4115, 0.6839],
        [0.0703, 0.5105, 0.9451, 0.2359, 0.1979, 0.3327]])
Shape of tensor: torch.Size([2, 6])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors

PyTorch tensors peform arithmetic operations intuitively. Tensors of similar shapes may be added, multipled, etc. Operations with scalars are distributed over the tensor.

In [14]:
ones = torch.ones(2,3)
print(ones)

twos = ones * 2 # every element is multipled by 2
print(twos)

threes = ones + twos # addition allowed because shapes are similar
print(threes) # tensors are added element-wise
print(threes.shape) # this has the same dimensions as input tensors

# Code below results in runtime error because there is no clean way to do element-wise arithmetic operations between two tensors of different shapes
# a1 = torch.rand(2,3)
# a2 = torch.rand(3,2)
# a3 = a1 + a2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


In [15]:
# Here is a small sample of the mathematical operations available on PyTorch tensors:
b = torch.rand(2,2) - 0.5 * 2 # values between -1 and 1
print('A random matrix, b: ')
print(b)

# Common mathematical operations are supported:
print('\nAbsolute value of b:')
print(torch.abs(b))

# Trigonometric functions
print('\nInverse sine of b:')
print(torch.asin(b))

# Linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of b:')
print(torch.det(b))
print('\nSingular value decomposition of b:')
print(torch.svd(b))

# Statistical and aggregate operations
print('\nAverage and standard deviation of b:')
print(torch.std_mean(b))
print('\nMaximum value of b:')
print(torch.max(b))

A random matrix, b: 
tensor([[-0.3854, -0.4001],
        [-0.4987, -0.0603]])

Absolute value of b:
tensor([[0.3854, 0.4001],
        [0.4987, 0.0603]])

Inverse sine of b:
tensor([[-0.3957, -0.4116],
        [-0.5221, -0.0604]])

Determinant of b:
tensor(-0.1763)

Singular value decomposition of b:
torch.return_types.svd(
U=tensor([[-0.7514, -0.6599],
        [-0.6599,  0.7514]]),
S=tensor([0.7062, 0.2496]),
V=tensor([[ 0.8761, -0.4821],
        [ 0.4821,  0.8761]]))

Average and standard deviation of b:
(tensor(0.1906), tensor(-0.3361))

Maximum value of b:
tensor(-0.0603)


In [16]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

tensor.device

device(type='cpu')

In [17]:
# Standard numpy-like indexing and slicing
tensor = torch.rand(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([0.8656, 0.5207, 0.6865, 0.3614])
First column:  tensor([0.8656, 0.6493, 0.2024, 0.7301])
Last column: tensor([0.3614, 0.0548, 0.4067, 0.0381])
tensor([[0.8656, 0.0000, 0.6865, 0.3614],
        [0.6493, 0.0000, 0.4762, 0.0548],
        [0.2024, 0.0000, 0.7191, 0.4067],
        [0.7301, 0.0000, 0.7357, 0.0381]])


In [18]:
# You can use torch.cat to concatenate a sequence of tensors along a given dimension
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.8656, 0.0000, 0.6865, 0.3614, 0.8656, 0.0000, 0.6865, 0.3614, 0.8656,
         0.0000, 0.6865, 0.3614],
        [0.6493, 0.0000, 0.4762, 0.0548, 0.6493, 0.0000, 0.4762, 0.0548, 0.6493,
         0.0000, 0.4762, 0.0548],
        [0.2024, 0.0000, 0.7191, 0.4067, 0.2024, 0.0000, 0.7191, 0.4067, 0.2024,
         0.0000, 0.7191, 0.4067],
        [0.7301, 0.0000, 0.7357, 0.0381, 0.7301, 0.0000, 0.7357, 0.0381, 0.7301,
         0.0000, 0.7357, 0.0381]])


In [19]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1.3511, 0.9088, 0.8159, 1.1508],
        [0.9088, 0.6514, 0.4962, 0.8265],
        [0.8159, 0.4962, 0.7235, 0.6924],
        [1.1508, 0.8265, 0.6924, 1.0758]])

In [20]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.7493, 0.0000, 0.4713, 0.1306],
        [0.4216, 0.0000, 0.2268, 0.0030],
        [0.0410, 0.0000, 0.5171, 0.1654],
        [0.5331, 0.0000, 0.5413, 0.0015]])

**Useful source to understand matrix multiplication: [matrixmultiplication.xyz](http://matrixmultiplication.xyz/)**



In [21]:
# If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

5.92598819732666 <class 'float'>


In [22]:
# Operations that store the result into the operand are called in-place
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.8656, 0.0000, 0.6865, 0.3614],
        [0.6493, 0.0000, 0.4762, 0.0548],
        [0.2024, 0.0000, 0.7191, 0.4067],
        [0.7301, 0.0000, 0.7357, 0.0381]]) 

tensor([[5.8656, 5.0000, 5.6865, 5.3614],
        [5.6493, 5.0000, 5.4762, 5.0548],
        [5.2024, 5.0000, 5.7191, 5.4067],
        [5.7301, 5.0000, 5.7357, 5.0381]])


**Note: In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.**

# Bridge with NumPy

In [23]:
# Tensor to NumPy array
t = torch.ones(10)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [24]:
# A change in the tensor reflects in the NumPy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [25]:
# NumPy array to Tensor
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [26]:
# Changes in the NumPy array reflects in the tensor
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
